name: bluetooth_classic
description: A Flutter plugin for Bluetooth Classic connectivity across Android and iOS platforms.
version: 0.1.0
homepage: https://github.com/yourusername/bluetooth_classic

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aclick.bluetooth_classic
        pluginClass: BluetoothClassicPlugin
      ios:
        pluginClass: BluetoothClassicPlugin
