name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build_iot:
    name: Build IoT App
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: |
          cd packages/core
          flutter pub get
          cd ../../apps/iot
          flutter pub get
      
      - name: Build for Dev
        if: github.ref == 'refs/heads/develop'
        run: |
          cd apps/iot
          cp .env.dev .env
          flutter build apk --debug
      
      - name: Build for Staging
        if: github.ref == 'refs/heads/main'
        run: |
          cd apps/iot
          cp .env.staging .env
          flutter build apk --profile
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: iot-app-build
          path: apps/iot/build/app/outputs/flutter-apk/*.apk
          retention-days: 7
  
  build_phone:
    name: Build Phone App
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true
      
      - name: Install dependencies
        run: |
          cd packages/core
          flutter pub get
          cd ../../apps/phone
          flutter pub get
      
      - name: Build for Dev
        if: github.ref == 'refs/heads/develop'
        run: |
          cd apps/phone
          cp .env.dev .env
          flutter build apk --debug
      
      - name: Build for Staging
        if: github.ref == 'refs/heads/main'
        run: |
          cd apps/phone
          cp .env.staging .env
          flutter build apk --profile
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: phone-app-build
          path: apps/phone/build/app/outputs/flutter-apk/*.apk
          retention-days: 7
